### PR TITLE
Automatic formatting/fixing

### PR DESCRIPTION
**Pull request by Ryu1845**
Goals are to improve general code quality.
I'm open to suggestions about sub-tasks or anything else.
This PR is set to draft until I think it might be ready to be merged, feel free to review/suggest changes.

### CODE REVIEW

**Comment by 152334H** [comment]
That's a big diff, but I'm assuming nothing breaking will happen if they're all just linters/fixers

**Comment by Ryu1845** [comment]
Yes, I haven't changed anything here yet.

**Comment by Ryu1845** [comment]
Thinking about it, separating the refactor and autolint/fix seems to be a better idea. The refactor is probably gonna take some time, and the automatic formatting would screw things up for other changes.

**Comment by 152334H** [comment]
do you have config files / commands to run for this so that I can upkeep it in the long term?

**Comment by Ryu1845** [comment]
```bash
ruff --fix-only .
isort **/**.py
black .
```

**Pull request merged**
